const FormSchema = require("./models/FormSchema");
const { logger } = require("./utils/logger");

const contactFields = [
  {
    id: "name",
    type: "text",
    label: "Your Full Name",
    placeholder: "e.g. Priya Sharma",
    required: true,
    group: "Contact Details",
  },
  {
    id: "phone",
    type: "phone",
    label: "Phone Number (WhatsApp Preferred)",
    placeholder: "+91 98765 43210",
    required: true,
    group: "Contact Details",
    helpText: "We will send customized decor mockups and pricing to this WhatsApp number.",
  },
  {
    id: "email",
    type: "email",
    label: "Email Address (Optional)",
    placeholder: "priya@example.com",
    required: false,
    group: "Contact Details",
  },
];

const purposeFormSeeds = [
  {
    key: "birthday",
    title: "Birthday Decoration",
    description: "Kids, milestone 1st, 18th, 30th, 50th, or romantic surprise birthdays.",
    version: 1,
    successMessage:
      "Thank you! Our birthday decor stylists will message you on WhatsApp within 30 minutes with tailored concepts and pricing.",
    notifyEmails: ["decorjoygurgaon@gmail.com"],
    fields: [
      ...contactFields,
      {
        id: "celebrant_name",
        type: "text",
        label: "Celebrant Name",
        placeholder: "e.g. Aarav",
        required: true,
        group: "Celebrant",
      },
      {
        id: "age",
        type: "number",
        label: "Age Turning",
        placeholder: "e.g. 5, 18, 30",
        required: false,
        min: 1,
        max: 120,
        group: "Celebrant",
      },
      {
        id: "theme",
        type: "select",
        label: "Decor Theme",
        placeholder: "Select a theme",
        required: true,
        options: [
          { value: "barbie", label: "Barbie & Pink Dream" },
          { value: "jungle_safari", label: "Jungle Safari & Animals" },
          { value: "superhero", label: "Marvel / DC Superhero" },
          { value: "space_odyssey", label: "Space & Astronauts" },
          { value: "unicorn", label: "Unicorn & Pastel Rainbow" },
          { value: "princess", label: "Royal Princess / Castle" },
          { value: "pastel_elegance", label: "Pastel Chic & Shimmer Wall" },
          { value: "car_racing", label: "Hot Wheels & Racing" },
          { value: "custom", label: "Custom Theme (Describe below)" },
        ],
        group: "Decor Theme",
      },
      {
        id: "custom_theme_desc",
        type: "text",
        label: "Describe Your Custom Theme",
        placeholder: "e.g. Harry Potter, Peppa Pig, Cocomelon...",
        required: false,
        showIf: { fieldId: "theme", equals: "custom" },
        group: "Decor Theme",
      },
      {
        id: "colours",
        type: "text",
        label: "Preferred Color Palette",
        placeholder: "e.g. Rose Gold & White, Chrome Blue & Silver, Sage Green & Peach",
        required: false,
        group: "Decor Theme",
      },
      {
        id: "need_cake_table",
        type: "radio",
        label: "Need a styled Cake Table / Plinth setup?",
        required: true,
        options: [
          { value: "yes", label: "Yes, cylinder plinths or styled cake table" },
          { value: "no", label: "No, backdrop & balloon arch only" },
        ],
        group: "Decor Elements",
      },
      {
        id: "need_photo_backdrop",
        type: "radio",
        label: "Need a dedicated Photo Booth Backdrop?",
        required: true,
        options: [
          { value: "yes", label: "Yes, with neon sign & ring/arch" },
          { value: "no", label: "No, simple room decor is enough" },
        ],
        group: "Decor Elements",
      },
      {
        id: "guest_count",
        type: "number",
        label: "Estimated Guest Count",
        placeholder: "e.g. 25",
        min: 1,
        max: 1000,
        group: "Venue & Logistics",
      },
      {
        id: "venue_type",
        type: "select",
        label: "Venue Type",
        required: true,
        options: [
          { value: "home", label: "Home / Apartment Living Room" },
          { value: "terrace", label: "Terrace / Rooftop" },
          { value: "society_hall", label: "Society Clubhouse / Hall" },
          { value: "banquet", label: "Banquet Hall" },
          { value: "restaurant", label: "Restaurant / Cafe" },
          { value: "outdoor", label: "Outdoor Lawn / Farmhouse" },
        ],
        group: "Venue & Logistics",
      },
      {
        id: "locality_pincode",
        type: "text",
        label: "Locality & Pincode in Gurgaon",
        placeholder: "e.g. Sector 57, Golf Course Ext Road - 122003",
        required: true,
        group: "Venue & Logistics",
      },
      {
        id: "event_date",
        type: "date",
        label: "Event Date",
        required: true,
        group: "Budget & Timing",
      },
      {
        id: "preferred_slot",
        type: "select",
        label: "Preferred Setup Time Slot",
        required: true,
        options: [
          { value: "morning", label: "Morning (09:00 AM - 01:00 PM)" },
          { value: "afternoon", label: "Afternoon (01:00 PM - 05:00 PM)" },
          { value: "evening", label: "Evening (05:00 PM - 09:00 PM)" },
          { value: "midnight", label: "Midnight Special (10:00 PM - 12:30 AM)" },
        ],
        group: "Budget & Timing",
      },
      {
        id: "budget_range",
        type: "select",
        label: "Approximate Budget Range",
        required: true,
        options: [
          { value: "under_5k", label: "Budget Friendly (Under ₹5,000)" },
          { value: "5k_to_10k", label: "Standard Celebration (₹5,000 - ₹10,000)" },
          { value: "10k_to_20k", label: "Grand Luxury Arch (₹10,000 - ₹20,000)" },
          { value: "above_20k", label: "Full Venue Transformation (₹20,000+)" },
        ],
        group: "Budget & Timing",
      },
      {
        id: "reference_image_link",
        type: "text",
        label: "Reference Image Link (Pinterest / Instagram / Drive)",
        placeholder: "https://...",
        required: false,
        group: "Additional Details",
      },
      {
        id: "notes",
        type: "textarea",
        label: "Additional Notes or Special Wishes",
        placeholder: "Tell us about neon sign wording, special balloon preferences, or timing constraints...",
        required: false,
        group: "Additional Details",
      },
    ],
  },
  {
    key: "anniversary",
    title: "Anniversary & Romantic Setup",
    description: "Intimate candlelight rooms, terrace cabanas, and milestone wedding anniversaries.",
    version: 1,
    successMessage:
      "Thank you! Our romantic decor planner will connect on WhatsApp with bespoke concepts.",
    notifyEmails: ["decorjoygurgaon@gmail.com"],
    fields: [
      ...contactFields,
      {
        id: "couple_names",
        type: "text",
        label: "Names of Couple",
        placeholder: "e.g. Priya & Rohan",
        required: true,
        group: "Couple Details",
      },
      {
        id: "years",
        type: "number",
        label: "Anniversary Year (e.g. 1st, 5th, 25th)",
        placeholder: "e.g. 10",
        required: false,
        group: "Couple Details",
      },
      {
        id: "romantic_level",
        type: "select",
        label: "Decor Styling Preference",
        required: true,
        options: [
          { value: "simple_romantic", label: "Sweet & Cozy (Bed balloons + rose petals + tea lights)" },
          { value: "premium_cabana", label: "Premium Romantic (Canopy/Cabana with fairy lights & neon sign)" },
          { value: "luxury_grand", label: "Grand Ballroom / Terrace Overhaul (LED pathway & photo gallery)" },
        ],
        group: "Decor Style",
      },
      {
        id: "is_surprise",
        type: "radio",
        label: "Is this a surprise celebration?",
        required: true,
        options: [
          { value: "yes", label: "Yes! Absolute Surprise (Contact via WhatsApp text ONLY)" },
          { value: "no", label: "No, partner is aware" },
        ],
        group: "Decor Style",
      },
      {
        id: "venue_type",
        type: "select",
        label: "Venue Type",
        required: true,
        options: [
          { value: "home_bedroom", label: "Home Bedroom / Living Room" },
          { value: "terrace", label: "Rooftop / Private Terrace" },
          { value: "hotel_suite", label: "Hotel Room / Suite" },
          { value: "private_dining", label: "Private Dining Room / Restaurant" },
        ],
        group: "Venue & Timing",
      },
      {
        id: "locality_pincode",
        type: "text",
        label: "Locality & Pincode in Gurgaon",
        placeholder: "e.g. DLF Phase 5 - 122009",
        required: true,
        group: "Venue & Timing",
      },
      {
        id: "event_date",
        type: "date",
        label: "Anniversary Date",
        required: true,
        group: "Budget & Timing",
      },
      {
        id: "budget_range",
        type: "select",
        label: "Budget Range",
        required: true,
        options: [
          { value: "under_5k", label: "Under ₹5,000" },
          { value: "5k_to_10k", label: "₹5,000 - ₹10,000" },
          { value: "10k_to_20k", label: "₹10,000 - ₹20,000" },
          { value: "above_20k", label: "₹20,000+" },
        ],
        group: "Budget & Timing",
      },
      {
        id: "notes",
        type: "textarea",
        label: "Personal Touches & Notes",
        placeholder: "Custom photo prints, favorite flowers, song requests...",
        group: "Additional Details",
      },
    ],
  },
  {
    key: "baby-shower",
    title: "Baby Shower & Welcome Baby",
    description: "Welcome little miracles with gentle pastel clouds, hot air balloons, and cute florals.",
    version: 1,
    successMessage:
      "Congratulations! Our celebration specialist will message on WhatsApp with baby welcome themes.",
    notifyEmails: ["decorjoygurgaon@gmail.com"],
    fields: [
      ...contactFields,
      {
        id: "celebration_type",
        type: "radio",
        label: "Celebration Type",
        required: true,
        options: [
          { value: "baby_shower", label: "Baby Shower / Mom-To-Be" },
          { value: "welcome_baby", label: "Welcome Baby Home" },
          { value: "gender_reveal", label: "Gender Reveal Party" },
        ],
        group: "Celebration Type",
      },
      {
        id: "baby_gender_palette",
        type: "select",
        label: "Color Palette & Gender",
        required: true,
        options: [
          { value: "baby_boy", label: "Baby Boy (Blue & Cloud White)" },
          { value: "baby_girl", label: "Baby Girl (Blush Pink & Peach)" },
          { value: "gender_neutral", label: "Gender Neutral (Boho Sage Green, Beige & Gold)" },
          { value: "reveal_duo", label: "Boy or Girl? (Pink & Blue Half-Half)" },
        ],
        group: "Celebration Type",
      },
      {
        id: "theme",
        type: "select",
        label: "Preferred Theme",
        options: [
          { value: "teddy_bear", label: "Teddy Bear on the Clouds" },
          { value: "hot_air_balloon", label: "Hot Air Balloon Journey" },
          { value: "elephant_safari", label: "Cute Baby Elephant" },
          { value: "boho_pampas", label: "Boho Pampas & Florals" },
          { value: "stork_arrival", label: "Stork & Moon Night" },
          { value: "other", label: "Other / Custom" },
        ],
        group: "Decor Theme",
      },
      {
        id: "venue_type",
        type: "select",
        label: "Venue Type",
        required: true,
        options: [
          { value: "home", label: "Home Setup" },
          { value: "hospital", label: "Hospital Suite Welcome" },
          { value: "society_hall", label: "Clubhouse / Society Hall" },
          { value: "banquet", label: "Banquet / Restaurant" },
        ],
        group: "Venue & Details",
      },
      {
        id: "locality_pincode",
        type: "text",
        label: "Locality & Pincode in Gurgaon",
        required: true,
        group: "Venue & Details",
      },
      {
        id: "guest_count",
        type: "number",
        label: "Approximate Guests",
        placeholder: "e.g. 30",
        group: "Venue & Details",
      },
      {
        id: "event_date",
        type: "date",
        label: "Event / Delivery Date",
        required: true,
        group: "Budget & Timing",
      },
      {
        id: "budget_range",
        type: "select",
        label: "Budget Range",
        required: true,
        options: [
          { value: "under_5k", label: "Under ₹5,000" },
          { value: "5k_to_10k", label: "₹5,000 - ₹10,000" },
          { value: "10k_to_20k", label: "₹10,000 - ₹20,000" },
          { value: "above_20k", label: "₹20,000+" },
        ],
        group: "Budget & Timing",
      },
      {
        id: "notes",
        type: "textarea",
        label: "Special Requests",
        placeholder: "Baby's name (if decided), entrance arch, customized signage...",
        group: "Additional Details",
      },
    ],
  },
  {
    key: "proposal",
    title: "Marriage Proposal Setup",
    description: "Breathtaking 'Marry Me' light letters, candle pathways, floral arches, and cold pyros.",
    version: 1,
    successMessage:
      "Exciting! Our luxury proposal coordinator will discreetly reach out on WhatsApp.",
    notifyEmails: ["decorjoygurgaon@gmail.com"],
    fields: [
      ...contactFields,
      {
        id: "venue_type",
        type: "select",
        label: "Proposal Venue",
        required: true,
        options: [
          { value: "private_terrace", label: "Private Rooftop / Terrace" },
          { value: "restaurant_cabana", label: "Restaurant Cabana / Lawn" },
          { value: "hotel_suite", label: "Luxury Hotel Suite" },
          { value: "scenic_outdoor", label: "Aravalli Scenic Spot / Farmhouse" },
          { value: "home", label: "Intimate At-Home Proposal" },
        ],
        group: "Venue",
      },
      {
        id: "needs_privacy",
        type: "radio",
        label: "Privacy Requirement",
        required: true,
        options: [
          { value: "100_percent_private", label: "100% Private (No bystanders or public crowd)" },
          { value: "semi_private", label: "Semi-Private / Reserved Cabana is fine" },
        ],
        group: "Venue",
      },
      {
        id: "neon_message",
        type: "text",
        label: "Message for Marquee / Neon Sign",
        placeholder: "Will You Marry Me? / Better Together / Forever & Always",
        required: true,
        group: "Decor Highlights",
      },
      {
        id: "special_effects",
        type: "select",
        label: "Special Highlights",
        options: [
          { value: "cold_pyros", label: "Cold Spark Pyros (Entry moment sparklers)" },
          { value: "rose_pathway", label: "Rose Petal Pathway with Lanterns" },
          { value: "heart_arch", label: "Giant Floral Heart Arch" },
          { value: "all_inclusive", label: "All of the Above (Complete Dream Setup)" },
        ],
        group: "Decor Highlights",
      },
      {
        id: "locality_pincode",
        type: "text",
        label: "Locality & Pincode in Gurgaon",
        required: true,
        group: "Venue & Timing",
      },
      {
        id: "event_date",
        type: "date",
        label: "The Big Date",
        required: true,
        group: "Budget & Timing",
      },
      {
        id: "budget_range",
        type: "select",
        label: "Budget Range",
        required: true,
        options: [
          { value: "6k_to_12k", label: "Romantic Cabana (₹6,000 - ₹12,000)" },
          { value: "12k_to_25k", label: "Grand Marquee & Pyro Setup (₹12,000 - ₹25,000)" },
          { value: "above_25k", label: "Ultra Luxury Cinema-Style (₹25,000+)" },
        ],
        group: "Budget & Timing",
      },
      {
        id: "notes",
        type: "textarea",
        label: "Timeline or Confidentiality Requests",
        placeholder: "Exact timing of surprise, photographer coordination, secret contact instructions...",
        group: "Additional Details",
      },
    ],
  },
  {
    key: "corporate",
    title: "Corporate & Office Decor",
    description: "Annual days, product launches, festival desk decor, stage backdrops, and milestones.",
    version: 1,
    successMessage:
      "Thank you! Our corporate event manager will send an itemized quotation and portfolio within 1 hour.",
    notifyEmails: ["decorjoygurgaon@gmail.com"],
    fields: [
      ...contactFields,
      {
        id: "company_name",
        type: "text",
        label: "Company / Organization Name",
        placeholder: "e.g. Zomato, Google, Innov8 Coworking",
        required: true,
        group: "Company Details",
      },
      {
        id: "event_type",
        type: "select",
        label: "Corporate Occasion",
        required: true,
        options: [
          { value: "foundation_day", label: "Company Foundation Day / Anniversary" },
          { value: "product_launch", label: "Product / Brand Launch" },
          { value: "festive_office", label: "Festive Office Celebration (Diwali, Xmas, Holi)" },
          { value: "townhall_stage", label: "Townhall / Annual Gala Stage Decor" },
          { value: "team_milestone", label: "Team Milestone / Funding Celebration" },
        ],
        group: "Event Details",
      },
      {
        id: "branding_needs",
        type: "select",
        label: "Branding Integration",
        required: true,
        options: [
          { value: "logo_balloons", label: "Brand Colors + Custom Logo Printed Balloons" },
          { value: "stage_entrance", label: "Stage Backdrop & Entrance Balloon Arch" },
          { value: "full_floor", label: "Complete Office Floor / Bay Transformation" },
        ],
        group: "Event Details",
      },
      {
        id: "attendees_count",
        type: "number",
        label: "Estimated Attendees / Employees",
        placeholder: "e.g. 150",
        required: true,
        min: 10,
        group: "Venue & Logistics",
      },
      {
        id: "office_address",
        type: "text",
        label: "Office / Venue Address in Gurgaon / NCR",
        placeholder: "e.g. Cyber City, DLF Phase 2 - 122002",
        required: true,
        group: "Venue & Logistics",
      },
      {
        id: "event_date",
        type: "date",
        label: "Event Date",
        required: true,
        group: "Budget & Timing",
      },
      {
        id: "budget_range",
        type: "select",
        label: "Budget Range (GST invoice provided)",
        required: true,
        options: [
          { value: "15k_to_35k", label: "₹15,000 - ₹35,000" },
          { value: "35k_to_75k", label: "₹35,000 - ₹75,000" },
          { value: "above_75k", label: "₹75,000+" },
        ],
        group: "Budget & Timing",
      },
      {
        id: "notes",
        type: "textarea",
        label: "Setup Time Window & Security Requirements",
        placeholder: "Late-night access permissions, loading dock access, brand guidelines...",
        group: "Additional Details",
      },
    ],
  },
  {
    key: "other",
    title: "Custom Event Celebration",
    description: "Housewarming, Bachelorette, Graduation, Welcome Party, or custom themes.",
    version: 1,
    successMessage:
      "Thank you! Our custom decor stylist will connect on WhatsApp with bespoke ideas.",
    notifyEmails: ["decorjoygurgaon@gmail.com"],
    fields: [
      ...contactFields,
      {
        id: "event_description",
        type: "textarea",
        label: "Tell us about your celebration",
        placeholder: "What are you celebrating? (e.g. Housewarming Pooja, Bride-to-be bachelorette, Graduation party...)",
        required: true,
        group: "Event Details",
      },
      {
        id: "theme_preference",
        type: "text",
        label: "Preferred Theme or Visual Style",
        placeholder: "e.g. Marigold Traditional, Chic Rose Gold, Modern Bohemian",
        required: false,
        group: "Event Details",
      },
      {
        id: "venue_type",
        type: "select",
        label: "Venue Type",
        required: true,
        options: [
          { value: "home", label: "Home / Flat" },
          { value: "terrace", label: "Terrace / Rooftop" },
          { value: "society_hall", label: "Society Clubhouse" },
          { value: "restaurant", label: "Restaurant / Cafe" },
          { value: "banquet", label: "Banquet Hall" },
          { value: "outdoor", label: "Lawn / Farmhouse" },
        ],
        group: "Venue",
      },
      {
        id: "locality_pincode",
        type: "text",
        label: "Locality & Pincode in Gurgaon",
        required: true,
        group: "Venue",
      },
      {
        id: "guest_count",
        type: "number",
        label: "Expected Guest Count",
        placeholder: "e.g. 40",
        group: "Venue",
      },
      {
        id: "event_date",
        type: "date",
        label: "Event Date",
        required: true,
        group: "Budget & Timing",
      },
      {
        id: "budget_range",
        type: "select",
        label: "Budget Range",
        required: true,
        options: [
          { value: "under_5k", label: "Under ₹5,000" },
          { value: "5k_to_10k", label: "₹5,000 - ₹10,000" },
          { value: "10k_to_20k", label: "₹10,000 - ₹20,000" },
          { value: "above_20k", label: "₹20,000+" },
        ],
        group: "Budget & Timing",
      },
      {
        id: "reference_image_link",
        type: "text",
        label: "Inspiration Image Link",
        placeholder: "https://...",
        group: "Additional Details",
      },
      {
        id: "notes",
        type: "textarea",
        label: "Special Requirements",
        placeholder: "Any special instructions or elements you'd love to have...",
        group: "Additional Details",
      },
    ],
  },
];

async function seedPurposeForms() {
  let seededCount = 0;
  for (const formSeed of purposeFormSeeds) {
    const existing = await FormSchema.findOne({ key: formSeed.key });
    if (!existing) {
      await FormSchema.create(formSeed);
      seededCount++;
    } else {
      // Keep up to date if fields change
      existing.title = formSeed.title;
      existing.description = formSeed.description;
      existing.fields = formSeed.fields;
      existing.successMessage = formSeed.successMessage;
      existing.notifyEmails = formSeed.notifyEmails;
      await existing.save();
    }
  }
  logger.info({ count: purposeFormSeeds.length, newSeeded: seededCount }, "Purpose form schemas seeded successfully");
  return purposeFormSeeds;
}

module.exports = {
  purposeFormSeeds,
  seedPurposeForms,
};
